#!/usr/bin/env bash
# install nginx on server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.back
echo "hello codeschool School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
sudo service nginx reload
