#!/usr/bin/env bash
# 301 redirect to orbitz home page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '26 i \ \n\trewrite ^/redirect_me https://orbitz.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
