#!/usr/bin/env bash
# install nginx on server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /usr/share/nginx/html/custom_404.html
sudo chmod 666 /usr/share/nginx/html/custom_404.html
sudo echo "Ceci n'est pas une page" | cat > /usr/share/nginx/html/custom_404.html
sudo sed -i '27 i \ \n\terror_page 404 /custom_404.html;\n        location = /custom_404.html {\n        root /usr/share/nginx/html;\n        internal;\n}' /etc/nginx/sites-available/default
sudo sed -i '26 i \ \n\trewrite ^/redirect_me https://orbitz.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
