#!/usr/bin/env bash
# prints codeschool 10 time using while, and prints Hi on 9th iteration

x=1
while [ $x -lt 11 ]
do
	if ((x == 9)); then
	   echo "codeschool School"
	   echo "Hi"
	   (( x++ ))
	else
	   echo "codeschool School"
	   (( x++ ))
	   fi
done