#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

hours=0
min=1
while(( hours <= 12 ))
do
    min=1
    echo "Hour: $hours"
    (( hours++ ))
    while(( min < 60 ))
    do
	echo $min
	((min++))
    done
done
