#!/usr/bin/env bash
#  Bash script that gives you information about the codeschool file

FILE="codeschool"
if [ -f "$FILE" ]; then
    echo "codeschool file exists"
    if [ -s "$FILE" ]; then
	echo "codeschool file is not empty"
    else
	echo "codeschool file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "codeschool file is a regular file"
    fi
else
    echo "codeschool file does not exist"
fi
