#!/usr/bin/env bash
# chnages localhost to 127.0.0.2
cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
