#!/usr/bin/env bash
# install haproxy  and adds server name to the responce header
sudo echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | sudo  tee /etc/apt/sources.list.d/backports.list
sudo apt-get update
sudo apt-get -y install haproxy -t trusty-backports
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo $'backend servers\n\tbalance roundrobin\n\tserver 124-web-01 66.70.184.169\n\tserver 124-web-02 142.44.164.124' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy reload
sudo service haproxy restart
