#!/usr/bin/env bash
# change nginx to run with user nginx instead of root
sudo pkill -9 apache2
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default
sudo chmod a+rwx -R /etc/nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo service nginx restart
